version: 2
jobs:
 # before_script:
  #  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
   # - emulator -avd test -no-skin -no-audio -no-window &
    #- android-wait-for-emulator
    #- adb shell input keyevent 82 &
  build:
    working_directory: ~/Pear_Studios #Because of our directories, this needs to be root haha yay

    docker:
      - image: circleci/android:api-29

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      #- script:
        #- sudo apt-get install libqt5widgets5
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: 
          name: Chmod permissions   #This is for if permission for Gradlew Dependencies fail!
          #working_directory: ~/Pear_Studios
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          #working_directory: ~/Pear_Studios/WalkIn
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run ourAndroidTests
          #working_directory: ~/Pear_Studios/WalkIn
          command: ./gradlew test
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/
      - store_test_results:
          path: app/build/test-results
#    test:
#      override:
       # start the emulator
#        - emulator -avd circleci-android22 -no-audio -no-window:
#            background: true
#            parallel: true
    # wait for it to have booted
#        - circle-android wait-for-boot
 # unlock the emulator screen
#        - sleep 30
#        - adb shell input keyevent 82
    # run tests  against the emulator.
        #- ./gradlew connectedAndroidTest -PdisablePreDex
    # copy the build outputs to artifacts
        #- cp -r app/build/outputs $CIRCLE_ARTIFACTS
    # copy the test results to the test results directory.
       # - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS

 #     - run:
  #        name: Lists installed targets
#          command: android list target
#          environment:
#          TERM: dumb
#      - run:
#          name: Show list of system-images
#          command: sdkmanager --list --verbose | grep system-images
#      - run:
#          name: Setup Emulator
#          command: sdkmanager "system-images;android-21;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-21;default;armeabi-v7a"
#      - run:
#          name: Launch Emulator
#          command: |
#                  cd ${ANDROID_HOME}/emulator;ls
#                  export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
#                  emulator -avd test -no-window -noaudio -no-boot-anim -no-window -accel on
#          background: true
#      - run:
#          name: Wait emulator
#          command: |
#              circle-android wait-for-boot
#              adb shell input keyevent 82
#      - run:
#          name: update android sdk
#          command: |
#              echo y | android update sdk --no-ui --all --filter tool,extra-android-m2repository,extra-google-google_play_services,extra-google-m2repository,android-26
#              echo y | android update sdk --no-ui --all --filter build-tools-26.0.0